theme: jekyll-theme-minimal
title: Xing Yee Gan Visualization Class Website
description: Interactive Plots
show_downloads: True
navigation: 
- title: Pyrazinamide Uptake
  url: /pza.html
- title: Isoniazid Uptake
  url: /niz.html
